### ISSUE TITLE
Branch-aware data snapshots

### ISSUE THREAD

**Issue by wlandau-lilly** [wlandau/gittargets#8]
## Prework

* [x] Read and agree to the [Contributor Code of Conduct](https://contributor-covenant.org/version/2/0/CODE_OF_CONDUCT.html) and [contributing guidelines](https://github.com/wlandau/gittargets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/wlandau/gittargets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] For any problems you identify, post a [minimal reproducible example](https://www.tidyverse.org/help/) like [this one](https://github.com/wlandau/targets/issues/256#issuecomment-754229683) so the maintainer can troubleshoot. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

`gittargets` could be capable of recording the code branch corresponding to the data commit. The current format of the data branch name is

```r
code=<HASH>
```

where it could be

```r
branch=<BRANCH_NAME>&commit=<HASH>
```

Then `tar_git_log()` could print out branch information and show data across all branches. That would give a full view of data snapshots across all code branches.

**Comment by wlandau** [comment]
Turns out the branch-specific data snapshot naming convention would just make it harder to check out snapshots later on. `tar_git_log()` should just look up info across all code branches.

**Comment by wlandau** [comment]
And viewing across branches while printing branch-specific info gets confusing fast (since a commit can have multiple refs). Better to go with https://github.com/wlandau/gittargets/commit/eafbe3a096fecbd8cd3cfcc9dc06d77ef2216de9, which leans into a per-branch `tar_git_log()` with a note in `Details:` explaining how to view all snapshots but with no branch info.
